// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhpcrtpevucuucoiodxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocGNydHBldnVjdXVjb2lvZHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTk1MjYsImV4cCI6MjA2MzY3NTUyNn0.DG1TzP4V85KseQZoXPAIe29kfO2zh2-uhHD0cLJ4Ctg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);